[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/"
]
